### ISSUE TITLE
using R in jupyter notebook with Docker

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#326] opened 2016-11-01 19:15 UTC
@kubu4 
I am not able to get jupyter notebook to talk to R using the old command 
```%load_ext rpy2.ipython```

Is there something in the docker file that already enables communication with R and I am missing it?
If not, is it possible to add the new IRkernel to the DockerFile.bio?
https://github.com/IRkernel/IRkernel

It is my understanding that this would then provide a drop down in jupyter notebook with R functionality.

**Comment by kubu4** [comment] 2016-11-01 19:23
Currently, there is no R kernel for Jupyter notebook in the Dockerfile.

Have you tried running the commands provided on that GitHub page? 

Those instructions should install the R kernel for Jupyter. After that, you should be able to start a Jupyter notebook and have the R kernel available to you in the new notebook dropdown menu.

**Comment by kubu4** [comment] 2016-11-01 19:24
To clarify my previous answer, you would enter all those commands inside your Docker container (from a R prompt). After you've run those commands, and exited the R session, then start your Jupyter notebook.

**Comment by kubu4** [comment] 2016-11-01 19:27
Finally, I'll look into adding this into the Dockerfile. 

I did have a previous R kernel install, but it was tied to an Anaconda (a software package manager) installation of R (which was in addition to a "default" installation R). The Anaconda installation of R screwed up how the system determined which R installation to use, which screwed up stuff with R Studio (which isn't currently installed with the Dockerfile for some other reasons).

**Comment by kubu4** [comment] 2016-11-03 14:20
I've assigned this to @seanb80. 

@seanb80 time to learn about Git branches! 

I've created a separate branch to allow you to work on getting the R kernel installation incorporated into the [dockerfile](https://github.com/sr320/LabDocs/blob/master/code/dockerfiles/Dockerfile.bio). Once you have it working, merge the r_kernel branch with the master branch.

Quick update on what I've done (and what needs fixing):
- Used apt-get to install ```littler``` package (R wrapper for command line - uses lowercase r to call R)

- Create a R script with the lines necessary to install R kernel (see link in @hputnam's post above) via a series of ```echo``` commands.

The R script fails with this message:

Can likely be resolved by adding ```repos = "http://cran.us.r-project.org"``` to the end of the ```install.packages``` command in the R script. However, I'd like to set the mirror permanently (via some config file, profile file, or sourced R script).

**Comment by seanb80** [comment] 2016-11-09 20:30
Have it functioning using the cran.us.r-project.org repo. Will try to find direct downloads of packages, or see if the package manager has the ability to specify versions.

**Comment by seanb80** [comment] 2016-11-09 21:18
Puzzling issue. 

install.packages() allows you to specify URLs to download packages from, allowing you to specify versions, but it disables the automatic dependency installation. 

Is it worth going through and finding links/correctly interacting versions (and whatever sub-dependencies exist) for the dozen or so dependencies and building the whole thing up from scratch?

**Comment by kubu4** [comment] 2016-11-09 21:27
What is the issue exactly?

Also, side note, please provide more specific commit messages.

**Comment by seanb80** [comment] 2016-11-09 21:41
Will do on the commit messages. 

The exact issue is calling install.packages(url to specific version file) causes the dependencies argument for install.packages() to automatically go to FALSE without an option to turn it back to TRUE as far as I can tell.

As an example, crayon requires the memoise package to run/install. When install.packages("crayon") is called, it goes and hunts down the memoise package and installs it. When install.packages(crayon url) is called, it just installs the crayon package, and since it doesn't have memoise present, the install fails.

I'm trying a workaround with devtools, will update on that shortly.

**Comment by kubu4** [comment] 2016-11-09 21:47
> calling install.packages(url to specific version file)

This will sound confusing and contradictory to what I've described as the purpose of using Docker (i.e. reproducibility), but don't bother with targeting specific package versions.

Just see if you can get the three lines in that R script (kernel_script_temp.R) to run. I'd recommend building the Docker container WITHOUT the R kernel stuff, and then try running those three commands (via command line) inside the container and see what happens.

**Comment by seanb80** [comment] 2016-11-09 21:53
Oh that part works in the current commit to the fork. 

Have a semi-work around for the dependencies issue using a devtools command install_version() which works for installing crayon and pbdZMQ (I chose the current version) but still requires devtools to be installed from the repo. 

Will update the GitHub version, making sure to use a better commit message this time!

**Comment by seanb80** [comment] 2016-11-09 22:15
Just uncovered a new bug. 

It looks like R inside the Jupyter notebook is trying to connect to the X11 server when it attempts to run a bit of code. Will see if I can figure out what is going on.

Jupyter notebook throws the following error message

```
I 22:12:08.034 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  :
  unable to start device PNG
Calls: <Anonymous> ... evaluate -> dev.new -> do.call -> <Anonymous> -> ok_device
In addition: Warning message:
In ok_device(filename, ...) : unable to open connection to X11 display ''
Execution halted
```

**Comment by kubu4** [comment] 2016-11-09 22:53
See if this GitHub issue helps: https://github.com/jupyter/notebook/issues/1775

**Comment by seanb80** [comment] 2016-11-11 19:59
Updated the r_kernel fork with a functioning script.

**Closed** 2016-11-15 22:07 UTC
Labels: Docker
